# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XMLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CsvToXml = channel.unary_unary(
                '/XMLService/CsvToXml',
                request_serializer=service__pb2.CsvRequest.SerializeToString,
                response_deserializer=service__pb2.XmlResponse.FromString,
                _registered_method=True)
        self.ValidateXml = channel.unary_unary(
                '/XMLService/ValidateXml',
                request_serializer=service__pb2.XmlRequest.SerializeToString,
                response_deserializer=service__pb2.ValidationResponse.FromString,
                _registered_method=True)
        self.XPathQuery = channel.unary_unary(
                '/XMLService/XPathQuery',
                request_serializer=service__pb2.QueryRequest.SerializeToString,
                response_deserializer=service__pb2.QueryResponse.FromString,
                _registered_method=True)


class XMLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CsvToXml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateXml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XPathQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CsvToXml': grpc.unary_unary_rpc_method_handler(
                    servicer.CsvToXml,
                    request_deserializer=service__pb2.CsvRequest.FromString,
                    response_serializer=service__pb2.XmlResponse.SerializeToString,
            ),
            'ValidateXml': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateXml,
                    request_deserializer=service__pb2.XmlRequest.FromString,
                    response_serializer=service__pb2.ValidationResponse.SerializeToString,
            ),
            'XPathQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.XPathQuery,
                    request_deserializer=service__pb2.QueryRequest.FromString,
                    response_serializer=service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'XMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('XMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XMLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CsvToXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/XMLService/CsvToXml',
            service__pb2.CsvRequest.SerializeToString,
            service__pb2.XmlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/XMLService/ValidateXml',
            service__pb2.XmlRequest.SerializeToString,
            service__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def XPathQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/XMLService/XPathQuery',
            service__pb2.QueryRequest.SerializeToString,
            service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
